### PR TITLE
use current versions on GitHub Actions, LHCI and Node

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by connorjclark** [comment]
Thanks! #839 does the node part- can you update; and also update the various references to these actions in `.md` files?

**Comment by coliff** [comment]
Heya @connorjclark - sorry I don't have this repo cloned locally and I won't have time to do that soon. Would you mind taking care of it?

**Comment by coliff** [comment]
related: Do you think it could be a good idea to add a dependabot config in the `.github` directory? It can help keep the GitHub Actions up to date. (and run tests in the PR that updates them to ensure all is working). e.g.

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
```

**Comment by paulirish** [comment]
> Thanks! #839 does the node part- can you update; and also update the various references to these actions in `.md` files?

done.

**Pull request merged**
