### PR TITLE
feat(utils): more gitlab build context support

### PR DESCRIPTION
**Pull request by candrews**
Additional support for build context environment variables provided by GitLab

See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

### CODE REVIEW

**Comment by candrews** [comment]
Build failure on macOS is an unrelated networking issue with that runner.

**Comment by candrews** [comment]
> @candrews haahahah what up dude!!!!!! great to see you 'round these parts. :)

Wow, how great to (virtually) run into you! I'm doing great, still busy being the change I want to see in the (software) world as best as I can, just as I've been doing since all that years ago when we last worked together :)

I hope things are going well with you!

**Comment by paulirish** [comment]
@candrews that sounds like the craig i know. :)   things good here, just been hacking on webperf tooling for ages. feel free to email me if i be helpful with any lighthouse-ci questions or whatever!

also geez.. first contribution to the repo is a pull request!? what a champ.

--------

for others: craig and i worked closely together for years at a small digital agency near boston over a decade ago.

**Comment by paulirish** [comment]
back to the PR... 

> Additional support for build context environment variables provided by GitLab
> 
> See [docs.gitlab.com/ee/ci/variables/predefined_variables.html](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)

@candrews  did you run into a case where there's a meaningful difference between the provided ENV values vs the fallback git commands?
I'm happy with the changes, but just wanted to capture if there was indeed a difference.

**Comment by candrews** [comment]
> did you run into a case where there's a meaningful difference between the provided ENV values vs the fallback git commands?

There is no meaningful difference as far as I can tell.

My goal is to eliminate the need to run `git` (or even have it installed), instead relying on the information provided in the GitLab CI provided environment variables.

**Review by paulirish — APPROVED** [review]
lgtm!

**Comment by candrews** [comment]
Woo hoo!

**Pull request merged**
