### PR TITLE
Allow setting chromePath in collect settings

### PR DESCRIPTION
**Pull request by remcohaszing**
This allows one to use the following example configuration:

```js
const puppeteer = require('puppeteer');

module.exports = {
  ci: {
    collect: {
      settings: {
        chromePath: puppeteer.executablePath(),
        chromeFlags: ['--headless'],
      },
      url: ['https://google.com'],
    },
  },
};
```

### CODE REVIEW

**Comment by remcohaszing** [comment]
I tried your suggestion in the first place, but it didn’t work.That’s the reason I created this pull request.

```sh
# Run in Docker, so we have a clean environment.
$ docker run --rm -ti node:12-slim bash
/# mkdir app
/# cd app
/app# yarn init
/app# yarn add @lhci/cli
/app# npx install-chrome-dependencies
/app# apt install vim
# All output from the commands above is irrelevant

/app# vim .lighthouserc.js
# Insert the configuration

/app# cat .lighthouserc.js
const puppeteer = require('puppeteer');

module.exports = {
  ci: {
    collect: {
      chromePath: puppeteer.executablePath(),
      numberOfRuns: 1,
      settings: { chromeFlags: ['--headless'] },
      url: ['https://www.google.com'],
    },
  },
};

/app# yarn lhci healthcheck
yarn run v1.22.4
$ /app/node_modules/.bin/lhci healthcheck
✅  .lighthouseci/ directory writable
✅  Configuration file found
❌  Chrome installation not found
    ERROR: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
Healthcheck failed!

# yarn lhci collect
yarn run v1.22.4
$ /app/node_modules/.bin/lhci collect
Error
    at new LauncherError (/app/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromePathNotSetError (/app/node_modules/chrome-launcher/dist/utils.js:42:9)
    at Object.linux (/app/node_modules/chrome-launcher/dist/chrome-finder.js:108:15)
    at Function.getInstallations (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:114:51)
    at Object.buildCommand (/app/node_modules/@lhci/cli/src/collect/collect.js:47:24)
    at Object.builder (/app/node_modules/@lhci/cli/src/cli.js:52:18)
    at Object.runCommand (/app/node_modules/yargs/lib/command.js:186:35)
    at Object.parseArgs [as _parseArgs] (/app/node_modules/yargs/yargs.js:1063:30)
    at Object.get [as argv] (/app/node_modules/yargs/yargs.js:1004:21)
error Command failed with exit code 1.
```

**Comment by patrickhulce** [comment]
Ah, thanks very much for the explanation! I wouldn't expect this to fix that bug though. That's a problem with the healthcheck command not respecting `chromePath` and looking for the installation on its own.

If you'd like to pick that up we basically want to change
https://github.com/GoogleChrome/lighthouse-ci/blob/67b6586640bef76b8e2f2a34446cbc326f4f07e0/packages/cli/src/healthcheck/healthcheck.js#L63-L66

to look like

```js
   label: 'Chrome installation found', 
   failureLabel: 'Chrome installation not found', 
   shouldTest: () => true, 
   test: opts => {
     if (opts.chromePath) return fs.existsSync(opts.chromePath);
     return ChromeLauncher.getInstallations().length > 0;
   },
```

but I can take that if it's too different :)

**Comment by remcohaszing** [comment]
I used the health check purely to troubleshoot the issue. Also the `lhci collect` command below failed.

**Comment by patrickhulce** [comment]
> Also the lhci collect command below failed.

I know it's tough to believe me at this point 😆, but that collect error is also unrelated to processing of `chromePath` in this way. It's an artifact produced when you're...

1. On linux
2. There are 0 Chrome installations available on normal paths
3. No puppeteer installed or `puppeteerScript` is not set

We should definitely also fix that wrinkle, I can take both of these :)

(As evidence, if you run `lhci collect --puppeteerScript=./go.js` in that docker container example you'll finally be able to launch the chrome executable you specified and run into the `--no-sandbox` issue)
```
$ /app/node_modules/.bin/lhci collect --puppeteerScript=./go.js
WARNING: collect.settings.chromeFlags option will be ignored.
WARNING: If you want chromeFlags with puppeteerScript, use collect.puppeteerLaunchOptions.args option.
Error: Failed to launch the browser process!
[0424/160110.413580:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:615:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:605:56)
    at Interface.emit (events.js:322:22)
    at Interface.close (readline.js:409:8)
    at Socket.onend (readline.js:187:10)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
error Command failed with exit code 1.
```

**Comment by remcohaszing** [comment]
I must say I’m not familiar with this project and I’m not sure what the issue means internally. I removed my changes, applied your suggestion, and force pushed.

**Comment by remcohaszing** [comment]
Thanks @patrickhulce!

Could you also release this please?

**Comment by remcohaszing** [comment]
This issue still exists.

[.lighthouserc.js](https://gitlab.com/appsemble/appsemble/-/blob/5d99eb4f0388b86f38fa95dfb17806b16ea4423f/.lighthouserc.js)

```js
const fs = require('fs');
const puppeteer = require('puppeteer');

module.exports = {
  ci: {
    collect: {
      chromePath: puppeteer.executablePath(),
      settings: {
        chromeFlags: ['--headless', 'CI' in process.env && '--no-sandbox'].filter(Boolean),
      },
      url: fs
        .readdirSync('apps')
        .map((path) => `https://${path}.appsemble.staging.appsemble.review`),
    },
    assert: {
      assertions: {
        'categories:accessibility': ['error', { minScore: 0.8 }],
        'categories:best-practices': ['error', { minScore: 0.7 }],
        'categories:performance': ['error', { minScore: 0.5 }],
        'categories:pwa': ['error', { minScore: 0.9 }],
        'categories:seo': ['error', { minScore: 1 }],
      },
    },
  },
};
```

[GitLab CI output](https://gitlab.com/appsemble/appsemble/-/jobs/572751873)

```js
$ yarn lhci collect
yarn run v1.22.4
$ /builds/appsemble/appsemble/node_modules/.bin/lhci collect
Running Lighthouse 3 time(s) on https://empty.appsemble.staging.appsemble.review
Run #1...failed!
Error: Lighthouse failed with exit code 1
    at ChildProcess.<anonymous> (/builds/appsemble/appsemble/node_modules/@lhci/cli/src/collect/lighthouse-runner.js:103:21)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Runtime error encountered: The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.
Error
    at new LauncherError (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromePathNotSetError (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:42:9)
    at Object.linux (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-finder.js:110:15)
    at Function.getInstallations (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:126:51)
    at Launcher.<anonymous> (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:159:48)
    at Generator.next (<anonymous>)
    at /builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at Launcher.launch (/builds/appsemble/appsemble/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:147:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by patrickhulce** [comment]
Ah drat, thanks @remcohaszing I know what's going on. I'll push a fix out today. You certainly uncovered quite the edge case. 3 different ways in which we fail if Chrome is not installed on the machine and you want to use puppeteer's chromium without using puppeteer 😅

**Pull request merged**
