### PR TITLE
Added DRONE_BRANCH to env

### PR DESCRIPTION
**Pull request by mlnchk**

### CODE REVIEW

**Comment by mlnchk** [comment]
@googlebot I signed it!

**Review by patrickhulce — COMMENTED** [review]
thanks very much @mlnchk! shall we add the other `DRONE_*` environment variables?

`DRONE_COMMIT_SHA`
`DRONE_REPO`

in particular, bummer that there's no build URL variable

**Comment by mlnchk** [comment]
@patrickhulce commit SHA already works (don't know why),  and where to use REPO I have not found. But just in case, I'll add them, thanks :)

**Comment by mlnchk** [comment]
build url does not exist because Drone is a self-hosted solution I think :(

**Review by patrickhulce — APPROVED** [review]
Thanks @mlnchk !

**Pull request merged**
