### PR TITLE
feature(server) Adding a method for obtaining statistics on a hash commit 

### PR DESCRIPTION
**Pull request by inerc**

### CODE REVIEW

**Comment by inerc** [comment]
@googlebot I signed it!

**Review by dipiash — APPROVED** [review]

**Comment by patrickhulce** [comment]
Thanks @inerc! Can you explain this use case? 

This information is already obtainable through finding the build ID associated with a hash and then fetching its statistics. (`/projects/:id/builds?hash=<hash>`, `/projects/:id/builds/:id/statistics`). We haven't explicitly opened up the API for arbitrary consumption, and I'm not inclined to add dedicated methods just to shortcut a single hop.

**Review by jeshio — APPROVED** [review]

**Review by Anton9408 — APPROVED** [review]

**Comment by patrickhulce** [comment]
More approvals won't move this along without addressing https://github.com/GoogleChrome/lighthouse-ci/pull/624#issuecomment-856805479 folks :)

**Comment by inerc** [comment]
> More approvals won't move this along without addressing [#624 (comment)](https://github.com/GoogleChrome/lighthouse-ci/pull/624#issuecomment-856805479) folks :)

The guys decided to help :) You're right @patrickhulce , I can do with the methods you described above.
For some reason it was not obvious to me. Can be closed pull request
Have a nice day.

**Pull request closed without merging**
